default_param = {
    "Autofluo channel": '488nm',
    "Staining channel": '561nm',
    'voxel_size': '4',
    'Brain_weight': '3500',
    'Brain_height': '2500',
    "Thickness": '75',
    "Network_input_z": '64',
    "Network_input_x_y": '256',
    'Train_total_num': '40',
    'Cut_index_x': '470',
    'Cut_index_y': '245',
    'Patch_weight_num': '10',
    'Patch_height_num': '7',
    'max_epochs': '10',
    'num_classes': '2',
    'test_batch_size': '1',
    'lr': '0.01',
    'save_patch_metrics': None,
    'save_metrics': None,
    'whole_brain_list':'pages/Whole_brain_seg/whole_brain_lists',
    'z_spacing': '1',
    'swin_in_channels': '16',
    'checkpoint_name': 'swin_T_checkpoint_22_01_09',
    'intensity_lower_differ': '0',
    'intensity_upper_differ': '1000',
    'point_min_size': '1',
    'big_object_size': '3000',
    'filter_area_lower':'1',
    'filter_area_upper':'27',
    'group_num': '6.25',
    'registration_output_name': None,
    'registration_param': 'tp_brain_registration_bspline.txt',
    'inverse_param': 'tp_inverse_bspline.txt'
}